# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gjeanmai <gjeanmai@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/01/01 19:31:57 by gjeanmai          #+#    #+#              #
#*   Updated: 2016/01/01 23:23:47 by                  ###   ########.fr       *#
#                                                                              #
# **************************************************************************** #

NAME = do-op

FLAGS = -Wall -Wextra -Werror

OPTS = -o $(NAME)

SRC = ft_atoi.c ft_ops.c ft_putchar.c ft_putnbr.c ft_putstr.c main.c

all:
	@gcc $(FLAGS) $(SRC) $(OPTS)

clean:
	rm -rf $(OBJ)
